import json
import os

from dotenv import load_dotenv
from openai import OpenAI


# Load variables from our .env file
load_dotenv()


# Create the OpenAI client using our API key
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


# Check whether the API key was loaded
if os.getenv("OPENAI_API_KEY"):
    print("API key loaded successfully!")
else:
    print("API key not found.")


# Roles we will eventually generate interviews for
roles = [
    "Data Scientist",
    "Machine Learning Engineer",
    "Data Analyst"
]


# For now, we are testing with only one role
role = "Data Scientist"


# Instructions that we will send to the LLM
prompt = f"""
You are a professional technical interviewer.

You are interviewing a candidate for a {role} position.

Ask one opening technical interview question.
"""


# Send our prompt to the OpenAI model
response = client.responses.create(
    model="gpt-5-mini",
    input=prompt
)


# Display the question generated by the model
print("\nGenerated Interview Question:")
print(response.output_text)